name: Resilience Review

on:
  pull_request:

jobs:
  resilience-review-en:
    name: "Resilience Review (en)"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: shinagawa-web/resilience-review-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          locale: en

  resilience-review-ja:
    name: "Resilience Review (ja)"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: shinagawa-web/resilience-review-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          locale: ja
